#!/bin/bash

#SBATCH --job-name=baseline_training    # Job name
#SBATCH --output=baseline-%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge    # Run on GPU queue
#SBATCH --gres=gpu:rtx2070:1    #rtx2070 is usually free

module load Python/3.12.3-GCCcore-13.3.0

cd ..
source .venv/bin/activate
python3 --version

echo "Running on $(hostname):"
nvidia-smi

python3 test_gpu.py
python3 baseline.py -e ${EPOCHS} -lr ${LEARNRATE} -f ${FINETUNE} -b ${BATCH_SIZE}