#!/bin/bash

#SBATCH --job-name=model-download       # Job name
#SBATCH --output=model-download.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=cores_any

module load Python/3.12.3-GCCcore-13.3.0

python3 --version

cd ..
source .venv/bin/activate

echo "Running on $(hostname):"

export HF_HOME=/home/niev/NER_proj/hf_cache
python3 -c "from transformers import AutoTokenizer, AutoModelForTokenClassification; \
           AutoTokenizer.from_pretrained('FacebookAI/xlm-roberta-base'); \
           AutoModelForTokenClassification.from_pretrained('FacebookAI/xlm-roberta-base')"